"""Hidden-content analyzer: HTML comments carrying instructions, zero-width
characters, bidi overrides ("Trojan Source"), and homoglyph spoofing."""

from __future__ import annotations

import re

from skillcheck.analyzers import AnalyzerRule, ScanContext
from skillcheck.models import FileKind, Finding, ParsedFile, Severity, escape_snippet

ANALYZER_RULES = [
    AnalyzerRule(
        "SC-HID-001",
        "Hidden instruction inside HTML comment",
        "high",
        "hidden-content",
        "An HTML comment — invisible in rendered markdown — contains an imperative instruction aimed at the agent.",
    ),
    AnalyzerRule(
        "SC-HID-002",
        "Zero-width characters concealed in text",
        "high",
        "hidden-content",
        "Zero-width unicode characters (U+200B–U+200F, U+2060, U+FEFF) can hide or split instructions invisibly.",
    ),
    AnalyzerRule(
        "SC-HID-003",
        "Unicode bidirectional override characters",
        "high",
        "hidden-content",
        "Bidi control characters (U+202A–U+202E, U+2066–U+2069) reorder displayed text — the 'Trojan Source' technique.",
    ),
    AnalyzerRule(
        "SC-HID-004",
        "Homoglyph characters mixed into ASCII text",
        "medium",
        "hidden-content",
        "Cyrillic/Greek lookalike letters inside otherwise-ASCII words can smuggle content past human review.",
    ),
]

#: Imperative / directive content inside an HTML comment that a human reader
#: never sees. Ordinary TODO/lint-directive comments must not match.
_COMMENT_DIRECTIVE_RE = re.compile(
    r"(?i)\b("
    r"do\s+not|don'?t|never|ignore|disregard|skip|hide|conceal|delete|remove|"
    r"send|post|upload|fetch|curl|wget|download|execute|run\s+the|run\s+this|"
    r"instead|secretly|silently|must\s+not\s+mention|tell\s+the\s+user|"
    r"you\s+(must|should|are)|before\s+(responding|answering)"
    r")\b"
)

#: Benign tool-directive comments to exempt (linters, formatters, our own suppressions).
_TOOL_DIRECTIVE_RE = re.compile(
    r"(?i)^\s*(markdownlint|prettier|eslint|editorconfig|toc|vale|alex|cspell|"
    r"skillcheck:|spell-checker|codegen|template|autogenerated|generated by)"
)

_ZERO_WIDTH = "​‌‍‎‏⁠﻿"
_BIDI = "‪‫‬‭‮⁦⁧⁨⁩"

_ZW_RE = re.compile(f"[{_ZERO_WIDTH}]")
_BIDI_RE = re.compile(f"[{_BIDI}]")

_ASCII_WORD = re.compile(r"[A-Za-z]")
_CONFUSABLE = re.compile(r"[Ѐ-ӿͰ-Ͽ]")  # Cyrillic + Greek
_WORD_RE = re.compile(r"[^\W\d_]+", re.UNICODE)


def analyze(parsed: ParsedFile, context: ScanContext) -> list[Finding]:
    if parsed.kind is not FileKind.MARKDOWN:
        return []
    findings: list[Finding] = []
    findings.extend(_check_comments(parsed))
    findings.extend(_check_invisible_chars(parsed))
    findings.extend(_check_homoglyphs(parsed))
    return findings


def _check_comments(parsed: ParsedFile) -> list[Finding]:
    findings = []
    for comment in parsed.metadata.get("html_comments", []):
        text = comment.text
        if not text or _TOOL_DIRECTIVE_RE.search(text):
            continue
        if _COMMENT_DIRECTIVE_RE.search(text):
            findings.append(
                Finding(
                    rule_id="SC-HID-001",
                    severity=Severity.HIGH,
                    category="hidden-content",
                    file=parsed.path,
                    line=comment.line,
                    message="Hidden instruction inside HTML comment",
                    snippet=escape_snippet(f"<!-- {text} -->"),
                    remediation="Remove the comment; agent instructions must be visible to the user.",
                )
            )
    return findings


def _check_invisible_chars(parsed: ParsedFile) -> list[Finding]:
    findings = []
    for line_no, line in enumerate(parsed.lines, start=1):
        text = line
        if line_no == 1 and text.startswith("﻿"):
            text = text[1:]  # a leading BOM alone is not an attack
        zw = _ZW_RE.findall(text)
        if zw:
            codes = ", ".join(sorted({f"U+{ord(c):04X}" for c in zw}))
            findings.append(
                Finding(
                    rule_id="SC-HID-002",
                    severity=Severity.HIGH,
                    category="hidden-content",
                    file=parsed.path,
                    line=line_no,
                    message=f"{len(zw)} zero-width character(s) ({codes}) concealed in text",
                    snippet=escape_snippet(text.strip()),
                    remediation="Strip zero-width characters; they serve no purpose in instruction files.",
                )
            )
        bidi = _BIDI_RE.findall(text)
        if bidi:
            codes = ", ".join(sorted({f"U+{ord(c):04X}" for c in bidi}))
            findings.append(
                Finding(
                    rule_id="SC-HID-003",
                    severity=Severity.HIGH,
                    category="hidden-content",
                    file=parsed.path,
                    line=line_no,
                    message=f"Bidirectional override character(s) ({codes}) reorder displayed text",
                    snippet=escape_snippet(text.strip()),
                    remediation="Remove bidi control characters (Trojan Source, CVE-2021-42574).",
                )
            )
    return findings


def _check_homoglyphs(parsed: ParsedFile) -> list[Finding]:
    findings = []
    for line_no, line in enumerate(parsed.lines, start=1):
        suspicious = [
            word
            for word in _WORD_RE.findall(line)
            if _ASCII_WORD.search(word) and _CONFUSABLE.search(word)
        ]
        if suspicious:
            findings.append(
                Finding(
                    rule_id="SC-HID-004",
                    severity=Severity.MEDIUM,
                    category="hidden-content",
                    file=parsed.path,
                    line=line_no,
                    message=f"Mixed-script homoglyph(s) in {len(suspicious)} word(s): "
                    + ", ".join(escape_snippet(w, 20) for w in suspicious[:3]),
                    snippet=escape_snippet(line.strip()),
                    remediation="Replace lookalike Cyrillic/Greek letters with their ASCII equivalents.",
                )
            )
    return findings
